
version: '3'

services:
########################## Hadoop ##########################
  namenode:
    image: hadoop-cluster
    hostname: namenode
    user: root
    command: ["./entrypoint.sh","namenode"]
    
    ports:
      - 9870:9870
    networks:
      - batch-queries-network
    
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048M

  datanode:
    image: hadoop-cluster
    user: root
    
    command: ["./entrypoint.sh","datanode"]
    
    depends_on:
      - namenode
    networks:
      - batch-queries-network
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  
  resourcemanager:
    image: hadoop-cluster
    hostname: resourcemanager
    user: root
    command: ["./entrypoint.sh","resourcemanager"]
    ports:
      - 8088:8088
    networks:
      - batch-queries-network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
      mode: replicated
      replicas: 3  

  
  nodemanager:
    image: hadoop-cluster
    hostname: nodemanager
    user: root
    command: ["./entrypoint.sh","nodemanager"]
    networks:
      - batch-queries-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

########################## Spark ##########################
  spark:
    image: spark-cluster
    hostname: spark
    command: ["spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./app:/app
    ports:
      - 7077:7077
      - 8080:8080
    networks:
      - batch-queries-network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M

  spark-worker:
    image: spark-cluster
    hostname: spark-worker
    command: ["spark-class", "org.apache.spark.deploy.worker.Worker","spark://spark:7077"]
    depends_on:
      - spark
    ports:
      - '8081'
    networks:
      - batch-queries-network

    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
      mode: replicated
      replicas: 3  



########################## nifi ##########################
  zooky-nifi:
    hostname: zooky-nifi
    container_name: zooky-nifi
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - batch-queries-network
  
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M

  nifi-node:
    image: apache/nifi:latest
    ports:
      - '8080'
    networks:
      - batch-queries-network
    volumes:
      - ./hadoop/config:/hadoop/conf
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zooky-nifi:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey 
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2048M
      mode: replicated
      replicas: 3



networks:
  batch-queries-network:

